
name: Java CICD with Maven

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout source
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn clean install -DskipTests

    - name: Login to Docker Hub
      run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}

    - name: Build docker image
      run: docker build -t idrisseaa/springboot-banking-app .
    - name: Publish image to dockerhub
      run: docker push idrisseaa/springboot-banking-app

  deploy:
    needs: build
    runs-on: [aws-ec2]
    steps:
      - name: Pull Image from docker hub
        run: docker pull idrisseaa/springboot-banking-app

      - name: Delete old container
        run: docker rm -f springboot-banking-app-container

      - name: Run docker container
        run: docker run -d -p 8080:8080 --name springboot-banking-app-container idrisseaa/springboot-banking-app