
name: Java CICD with Maven

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout source
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn clean install -DskipTests

    - name: Login to docker hub
      run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}

    - name: Build docker image
      run: docker build -t idrisseaa/banking-app .
    - name: Publish image to dockerhub
      run: docker push idrisseaa/banking-app:latest

  deploy:
    needs: build
    runs-on: [aws-ec2]
    steps:    
      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io
          sudo systemctl start docker
          sudo systemctl enable docker
          
      - name: Login to docker hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      
      - name: Pull Image from docker hub
        run: docker pull idrisseaa/banking-app

      - name: Delete old container
        run: docker rm -f banking-app-container

      - name: Run docker container
        run: docker run -d -p 8080:8080 --name banking-app-container idrisseaa/banking-app
